# **Импорт библиотеки NumPy**

In [1]:
import numpy as np

# **Примеры создания массивов**

#### Из обычных списков

In [2]:
arr = np.array([2, 7, 4])
print("Массив из обычного списка: ", arr)

Массив из обычного списка:  [2 7 4]


#### С использованием функций zeros, ones, eye, empty, arange

In [3]:
zero_arr = np.zeros((2, 4)) # создает двумерный массив из нулей размером 2 на 4 
print("1. Двумерный массив из нулей:\n", zero_arr)

one_arr = np.ones((2, 2, 3)) # создает трёхмерный массив из единиц размером 2 на 2 на 3
print("\n2. Трёхмерный массив из единиц:\n", one_arr)

eye_arr = np.eye(3) # создает единичную матрицу 3x3
print("\n3. Единичная матрица 3x3:\n", eye_arr)

empty_arr = np.empty(4) # создает пустой массив, заполненный мусором, оставшимся в памяти 
                        # (быстрее, чем заполнять нулями)
print("\n4. Массив, заполненный мусором: ", empty_arr)

arange_arr1 = np.arange(3, 27, 3) # создает массив последовательности (начало(по умолчанию 0),
                                  # конец(по умолчанию 1, не входит в последовательность), 
                                  # шаг(по умолчанию 1))
arange_arr2 = np.arange(27, 3, -3) # отрицательный шаг
arrange_arr3 = np.arange(5, 5, 2) # начало и конец последовательности совпадают
#arrange_arr4 = np.arange(2, 5, 0) # шаг равен 0 - выведет ошибку "division by zero"
print("\n5. Последовательности:\nПоследовательность с положительным шагом: ", arange_arr1)
print("Последовательность с отрицательным шагом: ", arange_arr2)
print("Последовательность, где начало и конец совпадают: ", arrange_arr3)

1. Двумерный массив из нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2. Трёхмерный массив из единиц:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

3. Единичная матрица 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Массив, заполненный мусором:  [6.23042070e-307 4.67296746e-307 1.69121096e-306 9.53813245e-312]

5. Последовательности:
Последовательность с положительным шагом:  [ 3  6  9 12 15 18 21 24]
Последовательность с отрицательным шагом:  [27 24 21 18 15 12  9  6]
Последовательность, где начало и конец совпадают:  []


# **Демонстрация атрибутов**

#### Вывод формы (shape) и типа данных (dtype)

In [4]:
print("Форма массива zero_arr: ", zero_arr.shape) # показывает форму массива zero_arr 
                                                  # (размер 2 на 4: 2 строки, 4 столбца)
print("Тип данных массива zero_arr: ", zero_arr.dtype) # показывает тип данных массива zero_arr

print("\nФорма массива one_arr: ", one_arr.shape)
print("Тип данных массива one_arr: ", one_arr.dtype)

print("\nФорма массива arange_arr1: ", arange_arr1.shape)
print("Тип данных массива arange_arr1: ", arange_arr1.dtype)

print("\nФорма массива empty_arr: ", empty_arr.shape)
print("Тип данных массива empty_arr: ", empty_arr.dtype)

Форма массива zero_arr:  (2, 4)
Тип данных массива zero_arr:  float64

Форма массива one_arr:  (2, 2, 3)
Тип данных массива one_arr:  float64

Форма массива arange_arr1:  (8,)
Тип данных массива arange_arr1:  int64

Форма массива empty_arr:  (4,)
Тип данных массива empty_arr:  float64


# **Примеры индексирования и срезов**

#### Получение отдельного элемента

In [5]:
arr_1 = np.arange(7)**7
print("Массив arr_1: ", arr_1)

print("\nПервый элемент массива arr_1: ", arr_1[0])
print("Последний элемент массива arr_1: ", arr_1[-1])

Массив arr_1:  [     0      1    128   2187  16384  78125 279936]

Первый элемент массива arr_1:  0
Последний элемент массива arr_1:  279936


#### Получение среза

In [6]:
print("Элементы массива arr_1 с 4 по 6: ", arr_1[3:6]) # конец не входит в диапазон
print("Четвертый и шестой элементы массива arr_1: ", arr_1[[3,5]])

print("\nМассив arr_1 в обратном порядке: ", arr_1[::-1])

# Изменим 4 и 5 элементы
arr_1[3:5] = 5
print("\nИзменённый массив arr_1: ", arr_1)

Элементы массива arr_1 с 4 по 6:  [ 2187 16384 78125]
Четвертый и шестой элементы массива arr_1:  [ 2187 78125]

Массив arr_1 в обратном порядке:  [279936  78125  16384   2187    128      1      0]

Изменённый массив arr_1:  [     0      1    128      5      5  78125 279936]


#### Извлечение подмассива с помощью среза

In [7]:
arr_2d = np.array([[1, 3, 5, 7, 9],
                  [2, 4, 6, 8, 10],
                  [11, 13,15, 17, 19],
                  [12, 14, 16, 18, 20]]) # создаём двумерный массив
print("Двумерный массив arr_2d:\n", arr_2d)
print("\nЭлемент на третьей строке в четвёртом столбце: ", arr_2d[2,3])
print("\nТретья и четвртая строки массива:\n", arr_2d[[2,3]])
print("\nЧетвёртый столбец третьей и четвёртой строк массива:\n", arr_2d[[2,3],3])
print("\nТретий столбец второй строки и четвёртый столбец четвёртой строки:\n", arr_2d[[1,3],[2,3]]) #
print("\nСо второго по четвертый столбец с третьей по четвёртую строку:\n", arr_2d[2:4, 1:4])
print("\nЧетвёртый столбец целиком:\n", arr_2d[:, 3])
print("\nСтроки массива с первой по третью:\n", arr_2d[: 3])

Двумерный массив arr_2d:
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [11 13 15 17 19]
 [12 14 16 18 20]]

Элемент на третьей строке в четвёртом столбце:  17

Третья и четвртая строки массива:
 [[11 13 15 17 19]
 [12 14 16 18 20]]

Четвёртый столбец третьей и четвёртой строк массива:
 [17 18]

Третий столбец второй строки и четвёртый столбец четвёртой строки:
 [ 6 18]

Со второго по четвертый столбец с третьей по четвёртую строку:
 [[13 15 17]
 [14 16 18]]

Четвёртый столбец целиком:
 [ 7  8 17 18]

Строки массива с первой по третью:
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [11 13 15 17 19]]


# **Примеры векторных операций и базовых статистик**

#### Поэлементное сложение и умножение, вычитание и деление массивов, возведение в степень, взятие остатка от деления

Массивы должны быть одинаковой формы, иначе получим ошибку.

In [8]:
a = np.array([3, 5, 7, 9, 11, 13])
b = np.array([27, 18, 23, 30, 7, 15])

print("Сложение массивовв a + b: ", a+b)
print("Умножение массивов a * b: ", a*b)
print("Вычитание массивов a - b: ", a-b)
print("Вычитание массивов b - a: ", b-a)
print("Деление массивов   a / b: ", a/b)
print("Деление массивов   b / a: ", b/a)

print("\nВозведение в степень a**2: ", a**2)
print("Возведение в степень a**b:", a**b)
print("Возведение в степень b**a:", b**a)

print("\nОстаток от деления a на b: ", a%b)
print("Остаток от деления b на a: ", b%a)

Сложение массивовв a + b:  [30 23 30 39 18 28]
Умножение массивов a * b:  [ 81  90 161 270  77 195]
Вычитание массивов a - b:  [-24 -13 -16 -21   4  -2]
Вычитание массивов b - a:  [24 13 16 21 -4  2]
Деление массивов   a / b:  [0.11111111 0.27777778 0.30434783 0.3        1.57142857 0.86666667]
Деление массивов   b / a:  [9.         3.6        3.28571429 3.33333333 0.63636364 1.15384615]

Возведение в степень a**2:  [  9  25  49  81 121 169]
Возведение в степень a**b: [       7625597484987        3814697265625  8922003266371364727
 -3535985420588157519             19487171    51185893014090757]
Возведение в степень b**a: [           19683          1889568       3404825447   19683000000000
       1977326743 1946195068359375]

Остаток от деления a на b:  [ 3  5  7  9  4 13]
Остаток от деления b на a:  [0 3 2 3 7 2]


#### Вычисление средней величины (mean), суммы (sum), минимума(min) и максимума (max)

In [9]:
print("Среднее значение массива a: ", a.mean())
print("Среднее значение массива b: ", b.mean())

print("\nСумма значений массива a", a.sum())
print("Сумма значений массива b", b.sum())

print("\nМинимум a: ", a.min(), ", максимум a: ", a.max())
print("Минимум b: ", b.min(), ", максимум b: ", b.max())

Среднее значение массива a:  8.0
Среднее значение массива b:  20.0

Сумма значений массива a 48
Сумма значений массива b 120

Минимум a:  3 , максимум a:  13
Минимум b:  7 , максимум b:  30
